# Generated by Django 3.2 on 2023-05-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w_date', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='September',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='October',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='November',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='March',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='June',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='July',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='January',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='February',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='December',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='August',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
        migrations.CreateModel(
            name='April',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.day')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.month_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_date.year')),
            ],
        ),
    ]
