# Generated by Django 3.2 on 2023-05-27 08:01

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('w_date', '0002_april_august_december_february_january_july_june_march_may_november_october_september'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('email', models.EmailField(blank=True, max_length=60, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100, validators=[django.core.validators.URLValidator()])),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('experience', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('education', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skills', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(blank=True, max_length=25, unique=True)),
                ('april', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.april')),
                ('august', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.august')),
                ('december', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.december')),
                ('february', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.february')),
                ('january', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.january')),
                ('july', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.july')),
                ('june', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.june')),
                ('march', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.march')),
                ('may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.may')),
                ('november', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.november')),
                ('october', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.october')),
                ('september', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_date.september')),
            ],
        ),
    ]
